% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\author{}
\date{\vspace{-2.5em}}

\begin{document}

Import data into R environment.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hosp<-}\KeywordTok{read.csv}\NormalTok{(}\StringTok{"HospitalCosts.csv"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(hosp, }\DataTypeTok{n=}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   AGE FEMALE LOS RACE TOTCHG APRDRG
## 1  17      1   2    1   2660    560
## 2  17      0   2    1   1689    753
## 3  17      1   7    1  20060    930
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  To record the patient statistics, the agency wants to find the age
  category of people who frequent the hospital and has the maximum
  expenditure.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(hosp}\OperatorTok{$}\NormalTok{AGE,}\DataTypeTok{main =} \StringTok{"Frequency of patients"}\NormalTok{,}\DataTypeTok{col =} \StringTok{"aquamarine"}\NormalTok{,}\DataTypeTok{xlab =} \StringTok{"Age"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Project2_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{attach}\NormalTok{(hosp) }
\NormalTok{AGE<-}\KeywordTok{as.factor}\NormalTok{(AGE) }
\KeywordTok{summary}\NormalTok{(AGE)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17 
## 307  10   1   3   2   2   2   3   2   2   4   8  15  18  25  29  29  38
\end{verbatim}

Conclusion 1: From the above results we conclude that infant category h
as the max hospital visits (above 300). The summary of Age gives us the
exact numerical output showing that Age 0 patients have the max visits
followed by Ages 15-17.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{aggregate}\NormalTok{(TOTCHG}\OperatorTok{~}\NormalTok{AGE,}\DataTypeTok{FUN=}\NormalTok{sum,}\DataTypeTok{data =}\NormalTok{ hosp) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    AGE TOTCHG
## 1    0 678118
## 2    1  37744
## 3    2   7298
## 4    3  30550
## 5    4  15992
## 6    5  18507
## 7    6  17928
## 8    7  10087
## 9    8   4741
## 10   9  21147
## 11  10  24469
## 12  11  14250
## 13  12  54912
## 14  13  31135
## 15  14  64643
## 16  15 111747
## 17  16  69149
## 18  17 174777
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{max}\NormalTok{(}\KeywordTok{aggregate}\NormalTok{(TOTCHG}\OperatorTok{~}\NormalTok{AGE,}\DataTypeTok{FUN=}\NormalTok{sum,}\DataTypeTok{data=}\NormalTok{hosp)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 678118
\end{verbatim}

Conclusion 2: Thus, we can conclude that the infants also have the
maximum hospital costs followed by Age groups 15 to 17, additionally we
can say confidently that number of hospital visits are proportional to
hospital costs.

\begin{enumerate}
\def\labelenumi{\Roman{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  In order of severity of the diagnosis and treatments and to find out
  the expensive treatments, the agency wants to find the diagnosis
  related group that has maximum hospitalization and expenditure.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{hist}\NormalTok{(APRDRG,}\DataTypeTok{col =} \StringTok{"cyan1"}\NormalTok{,}\DataTypeTok{main =} \StringTok{"Frequency of Treatments"}\NormalTok{,}\DataTypeTok{xlab =} \StringTok{"Trea tment Categories"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Project2_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{APRDRG_fact<-}\KeywordTok{as.factor}\NormalTok{(hosp}\OperatorTok{$}\NormalTok{APRDRG) }
\KeywordTok{summary}\NormalTok{(APRDRG_fact) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  21  23  49  50  51  53  54  57  58  92  97 114 115 137 138 139 141 143 204 206 
##   1   1   1   1   1  10   1   2   1   1   1   1   2   1   4   5   1   1   1   1 
## 225 249 254 308 313 317 344 347 420 421 422 560 561 566 580 581 602 614 626 633 
##   2   6   1   1   1   1   2   3   2   1   3   2   1   1   1   3   1   3   6   4 
## 634 636 639 640 710 720 723 740 750 751 753 754 755 756 758 760 776 811 812 863 
##   2   3   4 267   1   1   2   1   1  14  36  37  13   2  20   2   1   2   3   1 
## 911 930 952 
##   1   2   1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{which.max}\NormalTok{(}\KeywordTok{summary}\NormalTok{(APRDRG_fact)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 640 
##  44
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df<-}\KeywordTok{aggregate}\NormalTok{(TOTCHG}\OperatorTok{~}\NormalTok{APRDRG,}\DataTypeTok{FUN =}\NormalTok{ sum,}\DataTypeTok{data=}\NormalTok{hosp) }
\NormalTok{df }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    APRDRG TOTCHG
## 1      21  10002
## 2      23  14174
## 3      49  20195
## 4      50   3908
## 5      51   3023
## 6      53  82271
## 7      54    851
## 8      57  14509
## 9      58   2117
## 10     92  12024
## 11     97   9530
## 12    114  10562
## 13    115  25832
## 14    137  15129
## 15    138  13622
## 16    139  17766
## 17    141   2860
## 18    143   1393
## 19    204   8439
## 20    206   9230
## 21    225  25649
## 22    249  16642
## 23    254    615
## 24    308  10585
## 25    313   8159
## 26    317  17524
## 27    344  14802
## 28    347  12597
## 29    420   6357
## 30    421  26356
## 31    422   5177
## 32    560   4877
## 33    561   2296
## 34    566   2129
## 35    580   2825
## 36    581   7453
## 37    602  29188
## 38    614  27531
## 39    626  23289
## 40    633  17591
## 41    634   9952
## 42    636  23224
## 43    639  12612
## 44    640 437978
## 45    710   8223
## 46    720  14243
## 47    723   5289
## 48    740  11125
## 49    750   1753
## 50    751  21666
## 51    753  79542
## 52    754  59150
## 53    755  11168
## 54    756   1494
## 55    758  34953
## 56    760   8273
## 57    776   1193
## 58    811   3838
## 59    812   9524
## 60    863  13040
## 61    911  48388
## 62    930  26654
## 63    952   4833
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df[}\KeywordTok{which.max}\NormalTok{(df}\OperatorTok{$}\NormalTok{TOTCHG),] }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    APRDRG TOTCHG
## 44    640 437978
\end{verbatim}

Conclusion: Hence can conclude that category 640 has the maximum
hospitalizations by a huge number (267 out of 500), along with this it
also has the highest hospitalization cost.

\begin{enumerate}
\def\labelenumi{\Roman{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  To make sure that there is no malpractice, the agency needs to analyze
  if the race of the patient is related to the hospitalization costs.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hosp<-}\KeywordTok{na.omit}\NormalTok{(hosp)}

\CommentTok{#first we remove "NA"values }
\NormalTok{hosp}\OperatorTok{$}\NormalTok{RACE<-}\KeywordTok{as.factor}\NormalTok{(hosp}\OperatorTok{$}\NormalTok{RACE) }
\NormalTok{model_aov<-}\KeywordTok{aov}\NormalTok{(TOTCHG}\OperatorTok{~}\NormalTok{RACE,}\DataTypeTok{data =}\NormalTok{ hosp) }
\NormalTok{model_aov}\CommentTok{#ANOVA RESULTS }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
##    aov(formula = TOTCHG ~ RACE, data = hosp)
## 
## Terms:
##                       RACE  Residuals
## Sum of Squares    18593279 7523518505
## Deg. of Freedom          5        493
## 
## Residual standard error: 3906.493
## Estimated effects may be unbalanced
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(model_aov) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Df    Sum Sq  Mean Sq F value Pr(>F)
## RACE          5 1.859e+07  3718656   0.244  0.943
## Residuals   493 7.524e+09 15260687
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(hosp}\OperatorTok{$}\NormalTok{RACE)}\CommentTok{#getting max hospital cost per race }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   1   2   3   4   5   6 
## 484   6   1   3   3   2
\end{verbatim}

Conclusion: F value is quite low, which means that variation between
hospital costs among different races is much smaller than the variation
of hospital costs within each race, and P value being quite high shows
that there is no relationship between race and hospital costs, thereby
accepting the Null hypothesis. Additionally, we have more data for Race
1 in comparison to other races (484 out of 500 patients) which make the
observations skewed and thus all we can say is that there isn't enough
data to verify whether race of a patient affects hospital costs.

\begin{enumerate}
\def\labelenumi{\Roman{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  To properly utilize the costs, the agency has to analyze the severity
  of the hospital costs by age and gender for proper allocation of
  resources.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hosp}\OperatorTok{$}\NormalTok{FEMALE<-}\KeywordTok{as.factor}\NormalTok{(hosp}\OperatorTok{$}\NormalTok{FEMALE) }
\NormalTok{model_lm4<-}\KeywordTok{lm}\NormalTok{(TOTCHG}\OperatorTok{~}\NormalTok{AGE}\OperatorTok{+}\NormalTok{FEMALE,}\DataTypeTok{data =}\NormalTok{ hosp)}
\CommentTok{#calling Regression funtion }
\KeywordTok{summary}\NormalTok{(model_lm4) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = TOTCHG ~ AGE + FEMALE, data = hosp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -3403  -1444   -873   -156  44950 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  2719.45     261.42  10.403  < 2e-16 ***
## AGE            86.04      25.53   3.371 0.000808 ***
## FEMALE1      -744.21     354.67  -2.098 0.036382 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3849 on 496 degrees of freedom
## Multiple R-squared:  0.02585,    Adjusted R-squared:  0.02192 
## F-statistic: 6.581 on 2 and 496 DF,  p-value: 0.001511
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(hosp}\OperatorTok{$}\NormalTok{FEMALE) }\CommentTok{#comapring genders }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   0   1 
## 244 255
\end{verbatim}

Conclusion-Age has more impact than gender according to the P-values and
significant levels, also there are equal number of Females and Males and
on an average (based on the negative coefficient values) females incur
lesser hospital costs than males.

V. Since the length of stay is the crucial factor for inpatients, the
agency wants to find if the length of stay can be predicted from age,
gender, and race.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hosp}\OperatorTok{$}\NormalTok{RACE<-}\KeywordTok{as.factor}\NormalTok{(hosp}\OperatorTok{$}\NormalTok{RACE) }
\NormalTok{model_lm5<-}\KeywordTok{lm}\NormalTok{(LOS}\OperatorTok{~}\NormalTok{AGE}\OperatorTok{+}\NormalTok{FEMALE}\OperatorTok{+}\NormalTok{RACE,}\DataTypeTok{data =}\NormalTok{ hosp) }
\KeywordTok{summary}\NormalTok{(model_lm5) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = LOS ~ AGE + FEMALE + RACE, data = hosp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.211 -1.211 -0.857  0.143 37.789 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  2.85687    0.23160  12.335   <2e-16 ***
## AGE         -0.03938    0.02258  -1.744   0.0818 .  
## FEMALE1      0.35391    0.31292   1.131   0.2586    
## RACE2       -0.37501    1.39568  -0.269   0.7883    
## RACE3        0.78922    3.38581   0.233   0.8158    
## RACE4        0.59493    1.95716   0.304   0.7613    
## RACE5       -0.85687    1.96273  -0.437   0.6626    
## RACE6       -0.71879    2.39295  -0.300   0.7640    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.376 on 491 degrees of freedom
## Multiple R-squared:  0.008699,   Adjusted R-squared:  -0.005433 
## F-statistic: 0.6156 on 7 and 491 DF,  p-value: 0.7432
\end{verbatim}

Conclusion-p-values for all independent variables are quite high thus
signifying that there is no linear relationship between the given
variables, finally concluding the fact that we can't predict length of
stay of a patient based on age, gender and race.

\begin{enumerate}
\def\labelenumi{\Roman{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  To perform a complete analysis, the agency wants to find the variable
  that mainly affects the hospital costs.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model_lm6<-}\KeywordTok{lm}\NormalTok{(TOTCHG}\OperatorTok{~}\NormalTok{AGE}\OperatorTok{+}\NormalTok{FEMALE}\OperatorTok{+}\NormalTok{RACE}\OperatorTok{+}\NormalTok{LOS}\OperatorTok{+}\NormalTok{APRDRG,}\DataTypeTok{data =}\NormalTok{ hosp) }
\KeywordTok{summary}\NormalTok{(model_lm6) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = TOTCHG ~ AGE + FEMALE + RACE + LOS + APRDRG, data = hosp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -6367   -691   -186    121  43412 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  5024.9610   440.1366  11.417  < 2e-16 ***
## AGE           133.2207    17.6662   7.541 2.29e-13 ***
## FEMALE1      -392.5778   249.2981  -1.575    0.116    
## RACE2         458.2427  1085.2320   0.422    0.673    
## RACE3         330.5184  2629.5121   0.126    0.900    
## RACE4        -499.3818  1520.9293  -0.328    0.743    
## RACE5       -1784.5776  1532.0048  -1.165    0.245    
## RACE6        -594.2921  1859.1271  -0.320    0.749    
## LOS           742.9637    35.0464  21.199  < 2e-16 ***
## APRDRG         -7.8175     0.6881 -11.361  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2622 on 489 degrees of freedom
## Multiple R-squared:  0.5544, Adjusted R-squared:  0.5462 
## F-statistic:  67.6 on 9 and 489 DF,  p-value: < 2.2e-16
\end{verbatim}

Conclusion-Age and length of stay affect the total hospital costs.
Additionally, there is positive relationship between length of stay to
the cost, so with an increase of 1 day there is an addition of a value
of 742 to the cost.

\end{document}
